---
- name: create steamlink-autostart script
  become: yes
  ansible.builtin.copy:
    remote_src: true
    src: /usr/bin/steamlink
    dest: /usr/bin/steamlink-autostart
    owner: root
    mode: 0755

- name: create steamlink-autostart script
  become: yes
  ansible.builtin.lineinfile:
    path: /usr/bin/steamlink-autostart
    state: present
    insertbefore: 'latest=\$\(curl'
    line: '	sleep 10 # network start-up'

- name: ensure steamlink is started automatically
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    state: present
    line: '@steamlink-autostart'
