---
- name: install acme.sh
  become: yes
  get_url:
    url: https://get.acme.sh
    dest: "{{ acme_sh_path }}"
    mode: 0700

- name: make sure destination directory exists
  become: yes
  file:
    mode: 0755
    path: "{{ item | dirname }}"
    state: directory
  loop:
    - "{{ ssl_key_file }}"
    - "{{ ssl_fullchain_file }}"

- name: issue and install let's encrypt certificates
  become: yes
  shell:
    creates:
    - "{{ ssl_key_file }}"
    - "{{ ssl_fullchain_file }}"
    cmd: |
      systemctl stop nginx.service || true
      {{ acme_sh_path }} issue                              \
        --domain         "{{ ssl_domain }}"                 \
        --standalone                                        \
        --key-file       "{{ ssl_key_file }}"               \
        --fullchain-file "{{ ssl_fullchain_file }}"         \
        --reloadcmd      "systemctl restart nginx.service"
      test -f "{{ ssl_key_file }}" && test -f "{{ ssl_fullchain_file }}"

- name: ensure certificate are automaticlaly renewed
  become: yes
  shell: "{{ acme_sh_path }} install-cronjob"
