---
- name: install acme.sh
  become: yes
  get_url:
    url: https://get.acme.sh
    dest: "{{ acme_sh_path }}"
    mode: 0700

- name: issue and install let's encrypt certificates
  become: yes
  shell: |
    {{ acme_sh_path }} issue                              \
      --domain         "{{ ssl_domain }}"                 \
      --standalone                                        \
      --key-file       "{{ ssl_key_file }}"               \
      --fullchain-file "{{ ssl_fullchain_file }}"         \
      --reloadcmd      "systemctl restart nginx.service"
  register: acme_sh_issue

- name: check certificate installation
  assert:
    that: acme_sh_issue.stdout.find("-END CERTIFICATE-") != -1
    fail_msg: |
      {{ acme_sh_path }} failed to issue or install certificate(s) for '{{ ssl_domain }}'
      {{ acme_sh_issue.stderr }}
