- name: install steamlink through kodi
  hosts: pi

  tasks:
  - name: give sudo permission for kodi to run steamlink
    become: yes
    template:
      src: steamlink-kodi
      dest: /etc/sudoers.d/steamlink-kodi
      owner: root
      mode: 0644

  - name: stopping kodi
    become: yes
    systemd:
      name: kodi
      state: stopped

  - name: enable kodi "unkown source" installation
    become: yes
    replace:
      path: /home/kodi/.kodi/userdata/guisettings.xml
      regexp: <setting id="addons.unknownsources"[^>]*>false</setting>
      replace: <setting id="addons.unknownsources">true</setting>

  - name: download steamlink launcher plugin for kodi
    get_url:
      checksum: "sha256:5ef586c9b64e6a1b10a087571e39d5dab6d138e2f4fcde8ee00cc986981f9e41"
      url: "https://github.com/swetoast/steamlink-launcher/releases/download/0.0.6a/plugin.program.steamlink-v0.0.6a.zip"
      dest: /tmp/.

  - name: install steamlink launcher plugin
    unarchive:
      src: /tmp/plugin.program.steamlink-v0.0.6a.zip
      dst: /home/kodi/.kodi/addons

  - name: restart kodi
    become: yes
    systemd:
      name: kodi
      state: started
